### ISSUE TITLE
Simulator Support

### ISSUE THREAD

**Issue by cameronwebbable** [sqwiggle/webrtc-ios#1]

**Comment by cameronwebbable** [comment]
Simulator support seems to be working now! Hoping to get this up on travis now for sanity's sake.

**Comment by tommoor** [comment]
This would be fantastic :)

On Thu, Jul 17, 2014 at 1:53 PM, Cameron Webb notifications@github.com
wrote:

> Simulator support seems to be working now! Hoping to get this up on travis
> now for sanity's sake.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sqwiggle/webrtc-ios/issues/1#issuecomment-49364071.

## 

Tom Moor

http://tommoor.com
http://twitter.com/tommoor

**Comment by cameronwebbable** [comment]
Writing script ATM to combine ARMv7 and i386 libs into one, so we can use wherever the hell we want to!

**Comment by cameronwebbable** [comment]
Simulator support are go! I just need to get this bad boy to automatically upload somewhere and then this'll be good to go.

**Comment by cameronwebbable** [comment]
Closing this, moving to different issue for uploading libs.
