### ISSUE TITLE
Travis CI Deployment after Build

### ISSUE THREAD

**Issue by cameronwebbable** [sqwiggle/webrtc-ios#6]

**Comment by cameronwebbable** [comment]
Where we're at: the build now takes around an hour, thus Travis kills the build. Now we basically need to optimize build process for ios and simulator to run in parallel, which shouldn't take too long.

**Comment by cameronwebbable** [comment]
the build gets most of the way done, but when it tries to upload to travis, we get the following error:

```

/Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.6.5/lib/dpl/provider/s3.rb:35:in `chdir': No such file or directory - built_libs (Errno::ENOENT)
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.6.5/lib/dpl/provider/s3.rb:35:in `push_app'
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.6.5/lib/dpl/provider.rb:106:in `block in deploy'
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.6.5/lib/dpl/cli.rb:41:in `fold'
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.6.5/lib/dpl/provider.rb:106:in `deploy'
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.6.5/lib/dpl/provider/s3.rb:50:in `deploy'
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.6.5/lib/dpl/cli.rb:32:in `run'
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.6.5/lib/dpl/cli.rb:7:in `run'
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/dpl-1.6.5/bin/dpl:5:in `<top (required)>'
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/bin/dpl:23:in `load'
    from /Users/travis/.rvm/gems/ruby-1.9.3-p484/bin/dpl:23:in `<main>'
failed to deploy

```

built_libs is definitely still there, travis is changing the current working directory w/o logging it. ugh, more research...

**Comment by cameronwebbable** [comment]
This fully builds and deploys now. Hooray!

**Comment by smiller171** [comment]
How did you solve the issue with Travis not finding your build dir? I'm having the same issue in one of my repositories and have been fighting with it for an hour.

**Comment by timsavery** [comment]
same question as @smiller171

**Comment by adamshiervani** [comment]
@timsavery @smiller171 I had the same issue. Adding `skip_cleanup: true` worked for me!. 
Found it here - http://christopher-schuster.me/technology/2015/08/22/travis-ci-fun/

**Comment by cameronwebbable** [comment]
Apologies for no response on my end. I'm not on this project or with this organization anymore. 

After jogging my memory, skip_cleanup: true was what we used. Perhaps I should have better documented that at the time, but I was so excited to fix this issue I just said "HECK YEAH!" and closed the bug :).

**Comment by timsavery** [comment]
@cameronwebbable np...got there as well :) 

@adamshiervani thanks for the follow up!!
